INSERT INTO role (name) VALUES ('AUTHOR') ON DUPLICATE KEY UPDATE name = name;
INSERT INTO role (name) VALUES ('REVIEWER') ON DUPLICATE KEY UPDATE name = name;
INSERT INTO role (name) VALUES ('ADMIN') ON DUPLICATE KEY UPDATE name = name;
